### ISSUE TITLE
Add android toolchains 

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/polly#10]
https://code.google.com/p/android-cmake/

**Comment by headupinclouds** [comment]
Initial android-cmake toolchain pushed to polly/android branch as-is to get things going.

**Comment by ruslo** [comment]
Thanks, merged https://github.com/ruslo/polly/commit/e670b4c229ab50be9053c27bcbcc786e1cc8e291

**Comment by ruslo** [comment]
OpenCV Android toolchain: https://github.com/Itseez/opencv/blob/master/platforms/android/android.toolchain.cmake

**Comment by headupinclouds** [comment]
After looking at the diff, that seems to be a better starting point.  I'll
move the other one aside to serve as a reference and add the latest android
toolchain from OpenCV.  It appears to be identical but with a few small
updates.

```
#    LIBRARY_OUTPUT_PATH_ROOT should be set in cache to determine where
Android
#    libraries will be installed.
#    Default is ${CMAKE_SOURCE_DIR}, and the android libs will always be
#    under the ${LIBRARY_OUTPUT_PATH_ROOT}/libs/${ANDROID_NDK_ABI_NAME}
#    (depending on the target ABI). This is convenient for Android
packaging.
```

**Comment by ruslo** [comment]
https://github.com/taka-no-me/android-cmake

**Comment by ruslo** [comment]
CMake target properties:
* [ANDROID_GUI](http://www.cmake.org/cmake/help/v3.2/prop_tgt/ANDROID_GUI.html)
* [ANDROID_API_MIN](http://www.cmake.org/cmake/help/v3.2/prop_tgt/ANDROID_API_MIN.html)
* [ANDROID_API](http://www.cmake.org/cmake/help/v3.2/prop_tgt/ANDROID_API.html)

**Comment by ruslo** [comment]
Hello world sample: https://github.com/Discordia/android-cmake/tree/master/samples/hello-android-cmake

**Comment by ruslo** [comment]
one more example: https://github.com/Discordia/android-cmake-example

**Comment by pretyman** [comment]
Merge f930e1068083707533d55daed5f8f97a655585ff allows the toolchain to be used with hunter.

However there are still a few bits missing for the toolchain file in general:
Once the STL implementation is chosen, its lib directory is not added to the ANDROID_LINKER_FLAGS nor the linking flags to link to the library.

I updated on my repo a fix for this: f85df73ee55e2459f0219f84b837863c8797fee3 by creating an ANDROID_STL_LIB_DIR and adding it to the ANDROID_LINKER_FLAGS if gnustl_static is chosen, but would be nice to hear from whoever uses other options for ANDROID_STL on a better solution to deal with this.

ping @headupinclouds

**Comment by ruslo** [comment]
I've removed `Android*.cmake` from Polly (https://github.com/ruslo/polly/commit/31dcb9d3b41d482c174cd1881c76daff960050ad) since it's not toolchain related stuff.

Can be used by Hunter: https://github.com/ruslo/hunter/wiki/pkg.android.modules

**Comment by ruslo** [comment]
@headupinclouds https://github.com/ruslo/polly/commit/f89ebf3142a9cba6418fdc619833130abd1fcb6e I think https://github.com/taka-no-me/android-cmake is the original repo so probably version from OpenCV is older. So I guess we can move `android.toolchain.cmake.origin` back and remove `android.toolchain.cmake` (?)

**Comment by headupinclouds** [comment]
@ruslo  Agreed.  It looks like the taka-no-me repository is actively being updated ("authored 10 days ago").  I like the idea of using this one, since it will probably be easier to push and pull changes from upstream as needed.

**Comment by ruslo** [comment]
I've added `android-ndk-r10e` toolchain: https://github.com/ruslo/polly/wiki/Toolchain-list#android-ndk-xxx

Switch between different `ndk` versions was made similar to [iOS](https://github.com/ruslo/polly/wiki/Toolchain-list#ios) way. You can set different `ANDROID_NDK_xxx` environment variables and `build.py` will pick the right version and add `ANDROID_NDK` CMake variable.

Simple examples compile fine: https://github.com/ruslo/polly/tree/master/examples

**Comment by pretyman** [comment]
Guys, if you are going to revert to that toolchain, please be sure that it sets CMAKE_AR CMAKE_ANDROID_API 

And be aware that CMAKE_FORCE_C_COMPILER( "${CMAKE_C_COMPILER}" GNU ) sets the forced compiler which makes hunter fail.

**Comment by ruslo** [comment]
> Guys, if you are going to revert to that toolchain, please be sure that it sets CMAKE_AR CMAKE_ANDROID_API

I'm planning to cherry-pick your changes

**Comment by pretyman** [comment]
Sorry, I didn't mean CMAKE_AR, make sure it sets *CMAKE_C_PROCESSOR* is what I meant - sorry, I wrote it in a hurry. 

Anyway, as discussed in https://github.com/ruslo/polly/pull/16#issuecomment-105929330 it makes sense that these changes go to upstream and be reviewed by people who have been maintaining this file longer.

**Comment by pretyman** [comment]
This has been taken care of with the following pull request: https://github.com/taka-no-me/android-cmake/pull/53

**Comment by ruslo** [comment]
Usage example: https://github.com/forexample/android-cmake

**Comment by ruslo** [comment]
Well, looks like there is no need to create APK to run executable on device. It's possible to create simple console application and run it using `adb shell`. So it's easy to orginize testing with CMake's `add_test`:
* New function [android_add_test](https://github.com/hunter-packages/android-apk/commit/7577b236b6c547f03e3218d8a539bcc9f9b8550e) in [Android-Apk](https://github.com/ruslo/hunter/wiki/pkg.android.apk) project
* Usage [example](https://github.com/forexample/android-cmake/tree/master/00-console)
