### ISSUE TITLE
Why unset EFFECTIVE_PLATFORM_NAME 

### ISSUE THREAD

**Issue by lygstate** [ruslo/polly#107]
"-DTINYUNIT_TEST_CMD=$<TARGET_FILE:${TINYUNIT_TEST_TARGET_NAME}>"
This would result 

```
"-DTINYUNIT_TEST_CMD=/Users/travis/build/tinyunit/tinyunit/build/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/test_tinyunit_readme_sample.app/test_tinyunit_readme_sample"
```

**Comment by ruslo** [comment]
This is quite uninformative report :) Can you please provide more details about the problem? Thanks.

**Comment by lygstate** [comment]
How to choose -- [polly] Used toolchain: iOS 10.1 Universal (iphoneos + iphonesimulator) / clang / No code sign / c++11 support

iphonesimulator?
I want to building for iphonesimulator, how to do that.

**Comment by lygstate** [comment]
I means in command line.

**Comment by ruslo** [comment]
> I means in command line

`polly.py --iossim` will build simulator with i386 architecture (see `polly.py --help`).

**Comment by lygstate** [comment]
OK now I know how to do it directly in c/c++
