### ISSUE TITLE
Single toolchain for Android platform

### ISSUE THREAD

**Issue by xsacha** [ruslo/polly#110]
Instead of having a toolchain for every ABI, NDK version and API combination of Android, why not have a file that requires an environment variable to be set specifying the versions?

I use this myself because I can never end up with the same NDK versions. I'm not even sure why that exists at all.

Like this:
```
if(DEFINED POLLY_ANDROID_NDK_CMAKE_)
  return()
else()
  set(POLLY_ANDROID_NDK_CMAKE_ 1)
endif()

set(ANDROID_NDK_VERSION $ENV{ANDROID_NDK_VERSION})
set(ANDROID_NATIVE_API_LEVEL $ENV{ANDROID_NATIVE_API_LEVEL})
set(ANDROID_ABI $ENV{ANDROID_ABI})
set(ANDROID_NDK $ENV{ANDROID_NDK})

include("${CMAKE_CURRENT_LIST_DIR}/../polly/utilities/polly_clear_environment_variables.cmake")

include("${CMAKE_CURRENT_LIST_DIR}/../polly/utilities/polly_init.cmake")

polly_init(
    "Android NDK ${ANDROID_NDK_VERSION} / \
API ${ANDROID_NATIVE_API_LEVEL} / ${ANDROID_ABI} / \
c++11 support"
    "Unix Makefiles"
)

include("${CMAKE_CURRENT_LIST_DIR}/../polly/utilities/polly_common.cmake")

include("${CMAKE_CURRENT_LIST_DIR}/../polly/flags/cxx11.cmake") # before toolchain!

include("${CMAKE_CURRENT_LIST_DIR}/../polly/os/android.cmake")

```

**Comment by ruslo** [comment]
How
```
> ANDROID_NDK_VERSION=r10e ANDROID_NATIVE_API_LEVEL=21 ANDROID_ABI=mips build.py --toolchain android
```
is better than just
```
> build.py --toolchain android-ndk-r10e-api-21-mips
```
?

**Comment by xsacha** [comment]
When you are targeting API 24 or using NDK 13 or any other combination (there are 100s).

**Comment by ruslo** [comment]
> Do we produce 1000 more toolchain files instead of setting variable?

You're using all 1000 variants? Combinatorial explosion discussed [here](https://github.com/ruslo/polly/issues/20) and solution is out of scope of Polly functional (though I'm not 100% sure what it will looks like). For now workaround is to add only toolchains that you're **really** using.

**Comment by xsacha** [comment]
So every time I update my NDK, I should create new toolchains for every ABI I target (eg. armeabi-v7a, armeabi-v7a with NEON, arm64-v8a, x86_64)? Should I also commit it?
I have a machine with r13 and another with r13b.

**Comment by ruslo** [comment]
> So every time I update my NDK, I should create new toolchains for every ABI I target (eg. armeabi-v7a, armeabi-v7a with NEON, arm64-v8a, x86_64)?

Just like every time iOS version changed (`ios-*`), Visual Studio generator released (`vs-*`), OSX upgrade (`osx-*`), etc.

> Should I also commit it?

You mean send pull request? Yes, if you want :)

> What about local changes I need to make for toolchain such as exceptions/rtti?

It's a topic for separate discussion.

**Comment by xsacha** [comment]
Since r13, the NDK version can be detected by reading the $ANDROID_NDK/.source.properties file. This is how the Android NDK toolchain does it too.
This should help remove one combination in future at least.
They could be named like so: android-ndk-r13+-api-21-mips

**Comment by ruslo** [comment]
> Since r13, the NDK version can be detected by reading the $ANDROID_NDK/source.properties file

I guess this will not work for the cases when we need to have both `r13x` and `r13y` on the same machine.
