### ISSUE TITLE
How to change IPHONEOS_ARCHS and IPHONESIMULATOR_ARCHS value without modified polly source code ?

### ISSUE THREAD

**Issue by anylain** [ruslo/polly#115]
Hi, I'm green hand for cmake and polly. Very grateful to the development of polly such a good tool.

Recently in use, I encountered a problem, please take the time to guide.

When I use polly compile ios project, I hope to compile a fat lib for "arm7; arm64; x86_64"

I try to add parameters to the compile command
```
--fwd IPHONEOS_ARCHS = "armv7; arm64" IPHONESIMULATOR_ARCHS = "x86_64" \
--ios-multiarch --ios-combined
```

But does not work, the compiler is still trying to compile `armv7s`
I then tried to modify these environment variables in `CMakeLists.txt`
```
Set (IPHONEOS_ARCHS armv7; arm64)
Set (IPHONESIMULATOR_ARCHS x86_64)
```
Also did not work

I found that when I modified polly the `ios-10-2.cmake` file in the relevant configuration is finally working, but I feel this is not a good way to do so.

Will not amend the polly source code in the circumstances, there are other ways to achieve my goal?

**Comment by ruslo** [comment]
> I try to add parameters to the compile command

They will be overwritten by toolchain, this is why it's not working for you.

> there are other ways to achieve my goal?

You have to create separate toolchain if the default one doesn't fit your needs. For example take a look at `ios-9-0-i386-armv7` vs `ios-9-0-armv7`:
* https://github.com/ruslo/polly/blob/master/ios-9-0-i386-armv7.cmake
* https://github.com/ruslo/polly/blob/master/ios-9-0-armv7.cmake

Just for your information this approach is consistent with toolchain usage with Hunter package manager:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html

```
Toolchain file is the only way to apply global settings for 3rd party projects in Hunter.
```
