### ISSUE TITLE
How to use clang other than that provided by Apple?

### ISSUE THREAD

**Issue by piribes** [ruslo/polly#130]
Hi, is there a way to use Polly to generate a build using clang in /opt/local/ instead of that provided by Xcode?

**Comment by ruslo** [comment]
Check that `which clang++` returns `/opt/local/clang++`, in this case you can use `libcxx` toolchain (`clang++ -std=c++11 -stdlib=libc++`). Also since you're on OSX Polly will check which SDK is default in Xcode and add corresponding `CMAKE_OSX_SYSROOT` value.

**Comment by piribes** [comment]
Thank you
