### ISSUE TITLE
Android toolchains find local includes

### ISSUE THREAD

**Issue by xsacha** [ruslo/polly#132]
After the CMake 3.7.1+ codepath change for Android toolchains, they all stopped working.
Specifically, it was finding local include paths (/usr/include), which were then finding local arch-specific includes and causing the compilation to fail.
This affects all hunter/polly compiles for Android so I am not sure how anyone has this working. It even affects a fresh install for me.

Anyway, the fix was to add this to os/android.cmake (or the Android toolchain):

`set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)`

I can now successfully compile Android with latest CMake + Hunter + Polly with GCC or Clang.

Thanks.

**Comment by ruslo** [comment]
> so I am not sure how anyone has this working

Just for your info here is an succesful builds of OpenCV/Boost on Travis CI:
* https://travis-ci.org/ingenue/hunter/jobs/217544451
* https://travis-ci.org/ingenue/hunter/jobs/217998884

> it was finding local include paths (/usr/include)

3rd party management is out of the scope of Polly toolchains. If project with no dependencies works fine with Polly, then Polly is correct. 3rd party management is Hunter responsibility.

> Anyway, the fix was to add this to os/android.cmake (or the Android toolchain)

We are using standard CMake variables now so I prefer not to add any extra variables for no strong reason.
