### ISSUE TITLE
Error Cross-compiling Hunter Protobuf package using emscripten toolchain

### ISSUE THREAD

**Issue by madmongo1** [ruslo/polly#152]
This is a problem when interoperating Polly and Hunter.

First problem is that after specifying the toolchain:
${POLLY_LOCATION}/polly/emscripten-cxx11.cmake

and calling HunterGate, the first call to hunter_add_package fails, complaining that the following variables are not set:
CMAKE_C_ABI_COMPILED, CMAKE_CXX_ABI_COMPILED

a workaround is to add the following lines after the project() command:
 
if (NOT CMAKE_C_ABI_COMPILED)
    set(CMAKE_C_ABI_COMPILED ON)
endif ()
if (NOT CMAKE_CXX_ABI_COMPILED)
    set(CMAKE_CXX_ABI_COMPILED ON)
endif ()

Second (more serious) problem is that Hunter does not seem to realise that we are cross-compiling.

Therefore, when it builds protoc as part of the Protobuf package, it actually builds it as a javascript executable. I.e. it has cross-compiled it. This would not be a huge problem, I could just execute it with node.js, except that the protobuf installer does not realise that it the protoc.js also references the .memory file (the actual opcodes). These are left in the build tree, and of course Hunter deletes them.

Proposed Solution:

It would seem that there is an error in the emscripten toolchain. Hunter is unable to determine that it should use a local toolchain to build the protoc compiler, and the emscripten compiler to build my project and the protobuf libraries.

I don't know enough about the inner workings of hunter and cmake toolchains to propose a fix. Any help would be appreciated, or if you could post a patch which fixes it, this would be wonderful.

**Comment by ruslo** [comment]
> and calling HunterGate, the first call to hunter_add_package fails, complaining that the following variables > are not set:
> CMAKE_C_ABI_COMPILED, CMAKE_CXX_ABI_COMPILED

@pretyman Can you comment on this one?

> Therefore, when it builds protoc as part of the Protobuf package, it actually builds it as a javascript executable. I.e. it has cross-compiled it.

This one is about mixing toolchains. See this issue, you can find protobuf workaround there:
* https://github.com/ruslo/hunter/issues/495

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by mchiasson** [comment]
I can comment:
```
$ cmake . -DCMAKE_TOOLCHAIN_FILE=~/git/polly/emscripten-cxx11.cmake
-- [polly] Used toolchain: Emscripten Cross Compile / C++11

[hunter ** FATAL ERROR **] [Directory:/home/mchiasson/git/Test]
```
