### ISSUE TITLE
CHECK_TYPE_SIZE iOS error

### ISSUE THREAD

**Issue by xsacha** [ruslo/polly#169]
Recently, I have started getting this error when compiling for iOS (architectures: armv7;arm64).
Note: No simulators enabled.

 I haven't tracked down which commit of polly caused it but it seems fairly recent, as in this month or last month.

>  CHECK_TYPE_SIZE found different results, consider setting
>   CMAKE_OSX_ARCHITECTURES or CMAKE_TRY_COMPILE_OSX_ARCHITECTURES to one or no
>   architecture !

I get this when compiling dlib right now but it looks like any project causes this.

Have you got any insight as to why this might be happening?
It looks like it even happens with older polly versions so I am not sure if it was a change in hunter or polly that caused this.

**Comment by ruslo** [comment]
> Have you got any insight as to why this might be happening?

I guess `check_type_size` will work incorrectly if you're using toolchain with combined architectures. For `armv7` + `arm64` size of `long` will be `4` and `8` (I guess, not sure) and can't be determined on CMake configure stage, should be anallyzed at C++ compile stage.

> I am not sure if it was a change in hunter or polly that caused this

Maybe CMake? Maybe this one: https://github.com/ruslo/polly/commit/b6d9289043a0f2ec60b8b27a1aa229b96a349979?

**Comment by xsacha** [comment]
I went back to before this commit and still have the issue. I don't believe my version of CMake has ever changed (from 3.8.2) on this machine.
I had been successfully compiling my project with armv7 + arm64 for a while now. I can no longer do this even with an old polly due to this error.

**Comment by ruslo** [comment]
I don't know what/why is happenning. Try to track down the issue, history of iOS changes is here:
* https://github.com/ruslo/polly/commits/master/os/iphone.cmake

Plus take a look at changes of particular toolchain you're using. If you find the error and it's a valid case then test case can be added to `.travis.yml` to avoid such issues in future.

I guess Hunter URL/SHA1 is locked so it's probably not about Hunter.

**Comment by xsacha** [comment]
I'm still not sure why it started happening (Cmake version unchanged, polly version unchanged).
However, I have fixed all of the ones I have found or have PR pending for them.
So this can be closed.
