### ISSUE TITLE
xcode8 ios automatic provisioning

### ISSUE THREAD

**Issue by Mach1Studios** [ruslo/polly#198]
I keep getting an error asking to turn on Automatic signing by passing:
```Automatic signing is disabled and unable to
  generate a profile.  To enable automatic signing, pass
  -allowProvisioningUpdates to xcodebuild.
  Code Signing Error: Code signing is required for product type 'Application'
  in SDK 'iOS 11.0'
```

I am not sure how to do this via polly/cmake
I have tried many variations, everything works with nocodesign toolchains however with codesign things do not work despite have the Bundle Identifier and TeamID set in environment as well as the correct provisioning setup on apple's side.

**Comment by ruslo** [comment]
Start with simple trivial project and check all instruction for fixing errors from this page:
* http://polly.readthedocs.io/en/latest/toolchains/ios.html
