### ISSUE TITLE
Problem codesigning iOS 11.2 with Xcode 9.2 (9C40b)

### ISSUE THREAD

**Issue by robiwano** [ruslo/polly#231]
Having setup dev team and been able to compile the TestiOSProject app, I have a project where the CMake configure step fails with:
```
   /usr/bin/codesign --force --sign 91E950CF2DC18E042690FD08065CD6A3B114F984 --entitlements /Users/builder/buildslaves/dc/slave/dc-ios/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug-iphoneos/cmTC_8ae18.build/cmTC_8ae18.app.xcent --timestamp=none /Users/builder/buildslaves/dc/slave/dc-ios/build/CMakeFiles/CMakeTmp/Debug/cmTC_8ae18.app


  /Users/builder/buildslaves/dc/slave/dc-ios/build/CMakeFiles/CMakeTmp/Debug/cmTC_8ae18.app:
  unknown error -1=ffffffffffffffff

  Command /usr/bin/codesign failed with exit code 1

```
The developer certificate has access granted for Xcode, codesign and productbuild and I've (at least tried) unlocked the login.keychain from command line.

Help ?

**Comment by ruslo** [comment]
Have you tried:
* https://polly.readthedocs.io/en/latest/toolchains/ios/bundle-id.html
* https://polly.readthedocs.io/en/latest/toolchains/ios/errors/polly_ios_development_team.html
* https://polly.readthedocs.io/en/latest/toolchains/ios/errors/polly_ios_bundle_identifier.html

?

**Comment by robiwano** [comment]
Yup, I've tried all of those :(

**Comment by ruslo** [comment]
I have no other ideas, if you will find the solution don't forge to share.

**Comment by robiwano** [comment]
Hmm... I had to build for a "Generic iOS Device" to get the keychain access login prompt for codesign, after that, building from command line works.

**Comment by robiwano** [comment]
So in essence, I didn't RTFM :(
