### ISSUE TITLE
reason for clearing IPHONEOS_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by pokey909** [ruslo/polly#255]
polly_clear_environment_vairables.cmake clears the IPHONEOS_DEPLOYMENT_TARGET env var.

Since there is a comment just saying ```# !``` I assume there is a specific reason why we have to unset it. However, this prevents a possible parametrization of the ios toolchain which could include a code path like
```
string(COMPARE EQUAL "$ENV{IPHONEOS_DEPLOYMENT_TARGET}" "" _is_empty)
if(_is_empty)
  // do whatever (e.g. default)
else()
  set(IOS_DEPLOYMENT_SDK_VERSION "$ENV{IPHONEOS_DEPLOYMENT_TARGET}")
endif()
```

Is there a better way that allows this kind of parametrization to the toolchain via cmake defines?

**Comment by ruslo** [comment]
> Since there is a comment just saying # ! I assume there is a specific reason why we have to unset it

I don't remember details (commit was made 5 years ago) but yes, `# !` means the necessity of this change. Originally all of the environment variables from Xcode was cleared but few of them are really playing critical role, like `SDKROOT`:
* https://github.com/ruslo/polly/blob/6140caafd5087c6e7f91d7c7343ac82401c78346/utilities/polly_clear_environment_variables.cmake#L217

Deployment SDK version for iOS can be set by `IOS_DEPLOYMENT_SDK_VERSION` CMake variable, e.g.:
* https://github.com/ruslo/polly/blob/6140caafd5087c6e7f91d7c7343ac82401c78346/ios-10-3-dep-9-0-bitcode.cmake#L15

Which will be used to initialize `CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET`:
* https://github.com/ruslo/polly/blob/6140caafd5087c6e7f91d7c7343ac82401c78346/os/iphone.cmake#L115-L126

**Comment by pokey909** [comment]
I tried passing this variable via ```--fwd IOS_DEPLOYMENT_SDK_VERSION=9.0``` to polly which didn't work. I also tried to set it in a custom ```PreLoad.cmake``` to make sure it gets loaded before the toolchain. But it also did not get propagated.
The only place where I could set it seemed to be hardcoded in the toolchain itself.
This means I need to create another toolchain file for every change to the deployment target.

Do you have a suggestion how to do this more efficiently and avoid this combinatorial explosion effect?

**Comment by ruslo** [comment]
> This means I need to create another toolchain file for every change to the deployment target.

> Do you have a suggestion how to do this more efficiently and avoid this combinatorial explosion effect?

This is a know drawback (https://github.com/ruslo/polly/issues/20). I have some ideas but this involve completely new approach and a lot of work. Straightforward workaround at this moment just create another toolchain.

**Comment by ruslo** [comment]
Closing inactive discussion.
