### ISSUE TITLE
How to start for iOS?

### ISSUE THREAD

**Issue by zhouhao27** [ruslo/polly#263]
I'm planing to compile a C++ library for iOS. Where to start? Is there any tutorial for this? Thanks.

**Comment by ruslo** [comment]
There is no tutorials, you can find some useful info in this document:
* https://polly.readthedocs.io/en/latest/toolchains/ios.html

**Comment by zhouhao27** [comment]
So I should add those flags/variables in CMakeLists.txt for iOS? Or I add the flags at command line when I call cmake?

**Comment by ruslo** [comment]
This project is a collection of a CMake toolchains. There are toolchains that used to build iOS projects. Toolchain can be set by `-DCMAKE_TOOLCHAIN_FILE=/path/to/toolchain/ios*.cmake` or by `polly.py --toolchain ios*` helper script which is just a wrapper for running CMake.
