### ISSUE TITLE
Build failure on latest XCode (10A255)

### ISSUE THREAD

**Issue by jbzdarkid** [ruslo/polly#279]
It looks like the latest version of XCode has changed the "MacOSX10.13.sdk" alias to "MacOSX10.14.sdk". At the very least, this should change, but I'm wondering if it should just change to "MacOSX.sdk", which seems to be the base folder?

**Comment by ruslo** [comment]
Neither `MacOSX10.13.sdk` nor `MacOSX10.14.sdk` is hardcoded in toolchains so I'm not sure what is the problem exactly. Can you provide minimal example to reproduce the issue and all other details like system version, Xcode version, toolchain you're using, etc.

**Comment by jbzdarkid** [comment]
Specifically, `CMAKE_OSX_DEPLOYMENT_TARGET` is being set in https://github.com/ruslo/polly/blob/master/osx-10-13-make-cxx14.cmake

I can't easily provide a minimal example, but here's my system/xcode version (toolchain is the above):
```
$ xcodebuild -version
Xcode 10.1
Build version 10B61
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
```

**Comment by jbzdarkid** [comment]
Ah, I see -- we've only taken your latest release, and that was before this toolchain was out. Are you planning on making a release this year?

**Comment by jbzdarkid** [comment]
Thank you so much!
