### ISSUE TITLE
Add support for Apple's Project Catalyst

### ISSUE THREAD

**Issue by olliwang** [ruslo/polly#326]
Apple introduces Project Catalyst at WWDC 2019 to allows iOS apps running on macOS without heavily modifying the code. The problem is; currently, the toolchains build either iOS/Simulator or macOS libraries. To support Project Catalyst, we need a new toolchain to build fat libraries that include all of iOS, Simulator, and macOS architectures. Is it possible?

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by DimaRU** [comment]
Example of working toolchain:
```
unset(CMAKE_XCODE_ATTRIBUTE_INSTALL_PATH)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS "macosx")
set(CMAKE_XCODE_EFFECTIVE_PLATFORMS "-maccatalyst")
set(CMAKE_XCODE_ATTRIBUTE_MACOSX_DEPLOYMENT_TARGET "10.15")
set(CMAKE_C_FLAGS "-target x86_64-apple-ios13.0-macabi -Wno-overriding-t-option")
set(CMAKE_CXX_FLAGS "-target x86_64-apple-ios13.0-macabi -Wno-overriding-t-option")
```
