### ISSUE TITLE
Proposal: --framework 'identity'

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/polly#37]
I'd like to add an optional identity parameter for --framework option code signing.  If no argument is specified it can default to 'iPhone Developer' for backwards compatibility, but this can get in the way of distribution.  

https://github.com/ruslo/polly/blob/master/bin/detail/create_framework.py#L132

@ruslo: You implemented this feature, so I wanted to check with you before adding.

```
    sign_cmd = [
        'codesign', '--force', '--sign', 'iPhone Developer', framework_dir
    ]
    detail.call.call(sign_cmd, logging)
```

**Comment by ruslo** [comment]
@headupinclouds I think it's okay.

**Comment by headupinclouds** [comment]
pull request #40

**Comment by ruslo** [comment]
merged
