### ISSUE TITLE
Proposal: --info <info.plist> override as modifier for --framework option

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/polly#38]
Allow project specific override of polly/scripts/Info.plist. This will allow customization of CFBundleIdentifier and other parameters.

@ruslo: If this makes sense I can implement it and push.

https://github.com/ruslo/polly/blob/master/bin/detail/create_framework.py#L111
```
 framework_plist = os.path.join(framework_dir, 'Info.plist')
    shutil.copy(
        os.path.join(polly_root, 'scripts', 'Info.plist'),  <== override this
        framework_plist
    )
```

**Comment by ruslo** [comment]
> If this makes sense I can implement it and push

It make sense from the point of view that we are doing workaround for non-working iOS frameworks creation. Just like in https://github.com/ruslo/polly/issues/37 note that `Info.plist` can be controlled by CMake variable `MACOSX_BUNDLE_INFO_PLIST` and identity by `CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY`

**Comment by headupinclouds** [comment]
> Just like in #37 <https://github.com/ruslo/polly/issues/37> note that
Info.plist can be controlled by CMake variable MACOSX_BUNDLE_INFO_PLIST and
identity by CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY

You mean *if* the CMake ios framework wasn't broken, Right? (I'm assuming
these variables won't have any effect on the current polly code.)

**Comment by ruslo** [comment]
> You mean *if* the CMake ios framework wasn't broken, Right?

Yes, exactly.

**Comment by headupinclouds** [comment]
pull request #40

**Comment by ruslo** [comment]
merged
