### ISSUE TITLE
ios-nocodesign* does not work but for IOS_SDK_VERSION 8.1

### ISSUE THREAD

**Issue by skypjack** [ruslo/polly#46]
The `ios-nocodesign*.cmake` files contain a statement that forces the variable `IOS_SDK_VERSION` to 8.1.
We tested them at least with `IOS_SDK_VERSION` 9.1 and they work fine, but there is no explicitly way other than manually modify those files to change that parameter.
Is it possible to let the user to dynamically change it or update those file with a newer sdk version?
In the latter case, we can proceed with a pull request if needed.

**Comment by ruslo** [comment]
> The ios-nocodesign*.cmake files contain a statement that forces the variable IOS_SDK_VERSION to 8.1

Originally this toolchain was used for running jobs on Travis CI so I can skip developer's certificate installing step. Version should match the one that is set on Travis OSX machines.

> Is it possible to let the user to dynamically change it or update those file with a newer sdk version?

You can create new one `ios-nocodesign-9-1` and send a pull request.

**Comment by ruslo** [comment]
Closed by https://github.com/ruslo/polly/pull/47
