### ISSUE TITLE
"minor" changes to build.py command require --clear

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/polly#5]
I've noticed simple command line changes to build.py require rebuilding entirely due to the need for --clear on subsequent runs.  For example, after running

```
build.py 
```

cleanly, I then realized I wanted to install the output, so I tried

```
build.py --install
```

But this seems to trigger the warning

```
Looks like cmake arguments changed. Please remove build directory by adding '--clear'.
```

Which forces a full (possibly very length) rebuild.  The same is true with adding --verbose.  I suppose this requires more internal logic, but it does limit an otherwise very convenient build.py script.  Definitely not critical.

**Comment by ruslo** [comment]
Yep, I hit this issue myself too. I have to think about fixing this nicely. Sometimes this feature save me from a lot of headache (which is result of CMake cache magic).

**Comment by ruslo** [comment]
Fixed in branch 'develop'. List of variables ignored by checking:
* `CMAKE_VERBOSE_MAKEFILE`
* `POLLY_STATUS_DEBUG`
* `HUNTER_STATUS_DEBUG`
* `CMAKE_INSTALL_PREFIX`
