### ISSUE TITLE
Android MIPS architecture missed

### ISSUE THREAD

**Issue by skypjack** [ruslo/polly#56]
The Android MIPS architecture is missed in the list of available toolchains.
Is there a particular reason, thus it doesn't worth it to try to add such a toolchain and send a pull request?
I need it as an user and I'd be glad to contribute to the project if needed.

Thank you.

**Comment by ruslo** [comment]
> The Android MIPS architecture is missed in the list of available toolchains

No there are no reasons. Pull requests are welcome :)

**Comment by skypjack** [comment]
It makes perfectly sense indeed. :-)
Ok, maybe I'll have a try during the day and I'll send the pull request.
I'd close the issue/discussion (I suggest to tag it) posting the pull request number, for further references.
Thank you for the response.

**Comment by skypjack** [comment]
One more question: is the same valid for target armeabi?
If yes, I'm adding also that one with the next pull request or a separate one (as you prefer).

**Comment by ruslo** [comment]
> One more question: is the same valid for target armeabi?

Yes.

> one with the next pull request or a separate one

Separate is always better if possible.

**Comment by skypjack** [comment]
pull request for armeabi target - https://github.com/ruslo/polly/pull/57

**Comment by skypjack** [comment]
pull request for mips/mips64 - https://github.com/ruslo/polly/pull/58

**Comment by skypjack** [comment]
Thank you very much for the support and the patience.
