### ISSUE TITLE
Images in the Jenkins wiki are broken

### ISSUE THREAD

**Issue by pretyman** [ruslo/polly#67]
The Jenkin's page in the Wiki has all images with broken links: https://github.com/ruslo/polly/wiki/Jenkins 

I tried to edit it and but the filenames of the images are hashed and I could not make anything of them.

**Comment by ruslo** [comment]
> Wiki has all images with broken links

Yep, looks like mediacru.sh service is dead...

Now I use github as a image hosting service: https://github.com/ruslo/polly/wiki/Jenkins
