### ISSUE TITLE
Little suggestion: rename build.py to polly

### ISSUE THREAD

**Issue by xpol** [ruslo/polly#73]
How about rename `build.py` to `polly`?

> polly --reconfig --install --config RelWithDebInfo --toolchain osx-10-11-dep-10-10

**Comment by ruslo** [comment]
> How about rename build.py to polly?

Yes, I think it make sense. Does it conflicts with some other tools? For example if there will be two scripts `build.py` and `polly.py` will it solve problem? Also I can't run script without extension on Windows, so it should be `polly.py` instead of just `polly`.

@headupinclouds What do you think?

**Comment by headupinclouds** [comment]
:+1: I like the suggestion.  I'm also in favor of maintaining both build.py and polly.py initially to allow some time for transition.

**Comment by xpol** [comment]
Maybe just shell scripts `polly.bat` and `polly` which runs polly.py (or
build.py).
David Hirvonen <notifications@github.com>于2016年4月11日 周一22:55写道：

**Comment by ruslo** [comment]
> Maybe just shell scripts `polly.bat` and `polly` which runs polly.py (or build.py)

Okay, let it be `polly.bat` calling `polly.py` on Windows; `polly` shell script for calling `polly.py` on *nix; and `build.py` call `polly.py` for backward compatibility.

@xpol Feel free to work on this one and send me pull request.

**Comment by xpol** [comment]
#75 added.

The maybe we don't needs `polly.py`. just move it to `polly` ?

**Comment by ruslo** [comment]
> The maybe we don't needs polly.py. just move it to polly ?

Symmetry looks nicely :)
