### ISSUE TITLE
Build failed while run with caffe framework

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [ruslo/polly#8]
I tried with ios-8-2.cmake tool chain against "https://github.com/BVLC/caffe" to bulid caffe lib_a,dylip for iOS. Generate Xcode project completed. While build the Xcode project i got the below error
"/Users/Macpro_ios_v2/caffe/src/caffe/common.cpp:1:10: 'glog/logging.h' file not found"
while cross compiling mac to iOS only i am getting this issue. 
Environment: Xcode 6.2, iOS 8.2, CMake 3.2
Please help me to fix this issue.

**Comment by ruslo** [comment]
It's not a toolchain issue. Looks like you need to install third party library `glog`. Have you seen this project: https://github.com/ruslo/hunter?

**Comment by headupinclouds** [comment]
I'm working on getting a cmake wrapped version of glog in hunter, but haven't yet tested it.

Here is the cmake (google-glog)[https://github.com/emzeat/google-glog] fork that package is using.

Here is an initial (google-glog)[https://github.com/headupinclouds/hunter/blob/master/cmake/projects/glog/hunter.cmake] recipe.  This seems to build on iOS, but I haven't yet tested it.  Once that is working I will push it to the main ruslo/hunter repository.

**Comment by ruslo** [comment]
> I'm working on getting a cmake wrapped version of glog in hunter

It's not a glog only: http://caffe.berkeleyvision.org/installation.html

Also:
* cuda (does it working on iOS in general?)
* protobuf
* glog
* gflags
* hdf5
* leveldb
* snappy
* lmdb

> Once that is working I will push it to the main ruslo/hunter repository

opened issue:  https://github.com/ruslo/hunter/issues/80

**Comment by ruslo** [comment]
Anyway, I'm closing this since it's not a toolchain issue. This issue about 3rd party management. @karthikeyanchenniappan please subscribe to this bug: https://github.com/ruslo/hunter/issues/79 if you're interested

**Comment by karthikeyanchenniappan** [comment]
@ruslo ,@headupinclouds thanks for your update. Just for your info , i have installed below items on my MAC 10.10 through brew install , it works on caffe build for MAC OS X but throws  the above error for iOS only.
Installed locations for the below items are
/usr/local/include
/opt/local/include

cuda (does it working on iOS in general?)
protobuf
glog
gflags
hdf5
leveldb
snappy
lmdb

**Comment by ruslo** [comment]
> Just for your info , i have installed below items on my MAC 10.10 through brew install

@karthikeyanchenniappan if library is not header only it will not work for iOS, you need to build it from source
