### ISSUE TITLE
iOS version not found

### ISSUE THREAD

**Issue by hungbv** [ruslo/polly#80]
Hi ruslo!, thank you for your great project.
Currently, I'm working on Xcode 7.3. and I can only build when I choose iOS version is 9.3. when I build with other iOS version, errors will appear
 > cmake -H. -B_builds/ios-8-0 -GXcode -DCMAKE_TOOLCHAIN_FILE="${POLLY_ROOT}/ios-8-0.cmake" -DHUNTER_STATUS_DEBUG=ON

result:
iOS version `8.0` not found (64)
CMake Error at /Users/hungbv/Desktop/polly/utilities/polly_fatal_error.cmake:10 (message):
Call Stack (most recent call first):
  /Users/hungbv/Desktop/polly/os/iphone.cmake:63 (polly_fatal_error)
  /Users/hungbv/Desktop/polly/ios-8-0.cmake:36 (include)
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:9 (PROJECT)

Could you please let me know how to solve this problem? thank you :)

**Comment by ruslo** [comment]
> iOS version 8.0 not found (64)

Do you have iOS 8.0 SDK installed? See the table for mapping "Xcode version - iOS default SDK version" from wiki: https://github.com/ruslo/polly/wiki/Toolchain-list#ios However if you only need to have a minimum deployment target set to `8.0` you can create toolchain `ios-9-3-dep-8-0` with `set(IOS_DEPLOYMENT_SDK_VERSION 8.0)`. Take a look at example: https://github.com/ruslo/polly/blob/master/ios-9-1-dep-7-0-armv7.cmake

**Comment by hungbv** [comment]
oh, I found that I didn't install iOS 8.0 SDK yet. thank you :)

**Comment by ruslo** [comment]
> oh, I found that I didn't install iOS 8.0 SDK yet. thank you :)

Are you installing iOS 8.0 to Xcode 7.3 root? I'm not sure if it will work. Never tried it in fact.

**Comment by ruslo** [comment]
> Never tried it in fact

Let me know what happens :)

**Comment by hungbv** [comment]
Sorry, I haven't tried it yet. Network in my place was too slow. I used iOS 9.3 version, and then I reconfigure a little bit on my Xcode project :)

**Comment by ruslo** [comment]
Feel free to reopen on any updates.
