### ISSUE TITLE
Verbosity levels

### ISSUE THREAD

**Issue by yowidin** [ruslo/polly#81]
Currently the polly script either compiles everything silently or prints way too much information.

With the `--verbose` flag the `generate_command.append('-DCMAKE_VERBOSE_MAKEFILE=ON')` command within the polly.py script makes build output almost unreadable: it is very hard to notice any compiler warnings and errors while building. Of course you could simply pass a `--fwd CMAKE_VERBOSE_MAKEFILE=OFF` argument to the polly but I personally don't think that verbose output should be default behavior.

Without the `--verbose` flag where is literally no build progress at all.

My proposal is to introduce something like verbosity levels:
- silent - same as current behavior without the `--verbose` flag
- normal - normal CMake output without compiler arguments `-DCMAKE_VERBOSE_MAKEFILE=OFF`
- full - same as current behavior with the `--verbose` flag

**Comment by ruslo** [comment]
> My proposal is to introduce something like verbosity levels

seems good for me, feel free to send pull request
